apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cert-manager.community.tanzu.vmware.com.1.7.2
spec:
  refName: cert-manager.community.tanzu.vmware.com
  version: 1.7.2
  releasedAt: 2021-10-29T12:00:00Z
  releaseNotes: "cert-manager 1.7.2 https://github.com/jetstack/cert-manager/releases/tag/v1.7.2"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/cert-manager@sha256:6835074a07c582684d140258bde2254ae1943872bdc061c7d4e087cfbfbd4f5b
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
  capacityRequirementsDescription: "Varies significantly based on number of Certificate objects"
  valuesSchema:
    openAPIv3:
      title: cert-manager.community.tanzu.vmware.com.1.7.2 values schema
      examples:
        - namespace: cert-manager
      properties:
        namespace:
          type: string
          description: The namespace in which to deploy cert-manager.
          default: cert-manager
