apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kapp-controller.community.tanzu.vmware.com.0.41.2
spec:
  refName: kapp-controller.community.tanzu.vmware.com
  version: 0.41.2
  releaseNotes: "kapp-controller 0.41.2 https://github.com/vmware-tanzu/carvel-kapp-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/kapp-controller@sha256:c0c407116db8d8aee11ba6f0cc99eec62b65e20398c486657b5ca6a03e8c8fbd
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
